[package]
name = "quantum_error_correction"
version = "0.1.0"
edition = "2021"

[dependencies]
num-complex = "0.4.3"
ndarray = "0.15.4"
rand = "0.8.5"
plotters = { version = "0.3.0", default-features = false, features = ["svg_backend", "line_series"] }
